/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.CourseBUS;
import BUS.DepartmentBUS;
import BUS.OnlineCourseBUS;
import BUS.OnsiteCourseBUS;
import DTO.CourseDTO;
import DTO.DepartmentDTO;
import DTO.OnlineCourseDTO;
import DTO.OnsiteCourseDTO;
import GUI.MainForm;
import GUI.MainForm;
import java.sql.Array;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;

/**
 *
 * @author ANH KHOA
 */
public class FormCourse extends javax.swing.JFrame {
    private CourseBUS courseBUS = new CourseBUS();
    private OnlineCourseBUS onlineCourseBUS = new OnlineCourseBUS();
    private OnsiteCourseBUS onsiteCourseBUS = new OnsiteCourseBUS();
    private DepartmentBUS departmentBUS = new DepartmentBUS();
    String func;
    JTable table;
    /**
     * Creates new form FormDetailCourse
     */
    public FormCourse(String id, String func, JTable jTable) {
        this.func = func;
        table = jTable;
        
        
        initComponents();
        if(func.equals("show")){
            jButton1.setText("Edit");
            renderDataFormShow(id);
        }
        else{
            txt_url.setEditable(false);
            txt_Location.setEditable(false);
            txt_Time.setEditable(false);
            txt_Days.setEditable(false);
            renderDataFormAdd();
        }
        setLocationRelativeTo(null);  
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        information_panel = new javax.swing.JPanel();
        txt_title = new javax.swing.JTextField();
        txt_Credit = new javax.swing.JTextField();
        jcb_deparmentID = new javax.swing.JComboBox<>();
        txt_courseID = new javax.swing.JLabel();
        jcb_Online = new javax.swing.JCheckBox();
        jcb_onsite = new javax.swing.JCheckBox();
        panel_typeCourse = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt_url = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txt_Location = new javax.swing.JTextField();
        txt_Days = new javax.swing.JTextField();
        txt_Time = new javax.swing.JTextField();
        panel_btn = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel1.setLayout(new java.awt.BorderLayout());

        information_panel.setBackground(new java.awt.Color(255, 255, 255));
        information_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        information_panel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        information_panel.setName(""); // NOI18N

        txt_title.setBorder(javax.swing.BorderFactory.createTitledBorder("Title"));
        txt_title.setPreferredSize(new java.awt.Dimension(69, 40));
        txt_title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_titleActionPerformed(evt);
            }
        });

        txt_Credit.setBorder(javax.swing.BorderFactory.createTitledBorder("Credits"));

        jcb_deparmentID.setBorder(javax.swing.BorderFactory.createTitledBorder("Department ID"));
        jcb_deparmentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_deparmentIDActionPerformed(evt);
            }
        });

        txt_courseID.setBorder(javax.swing.BorderFactory.createTitledBorder("Course ID"));

        jcb_Online.setText("Online Course");
        jcb_Online.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_OnlineActionPerformed(evt);
            }
        });

        jcb_onsite.setText("Onsite Course");
        jcb_onsite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_onsiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout information_panelLayout = new javax.swing.GroupLayout(information_panel);
        information_panel.setLayout(information_panelLayout);
        information_panelLayout.setHorizontalGroup(
            information_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(information_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(information_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcb_deparmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_courseID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_Online))
                .addGap(29, 29, 29)
                .addGroup(information_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcb_onsite)
                    .addComponent(txt_title, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Credit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        information_panelLayout.setVerticalGroup(
            information_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(information_panelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(information_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(information_panelLayout.createSequentialGroup()
                        .addComponent(txt_title, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(information_panelLayout.createSequentialGroup()
                        .addComponent(txt_courseID, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(information_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Credit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_deparmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(information_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_Online)
                    .addComponent(jcb_onsite))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.add(information_panel, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        panel_typeCourse.setBackground(new java.awt.Color(255, 255, 255));
        panel_typeCourse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        panel_typeCourse.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Online Course", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        txt_url.setBorder(javax.swing.BorderFactory.createTitledBorder("URL"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_url, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txt_url, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        panel_typeCourse.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Onsite Course", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        txt_Location.setBorder(javax.swing.BorderFactory.createTitledBorder("Location"));

        txt_Days.setBorder(javax.swing.BorderFactory.createTitledBorder("Days"));

        txt_Time.setBorder(javax.swing.BorderFactory.createTitledBorder(" Time (yyyy-MM-dd HH:mm:ss)"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_Location)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_Days, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txt_Location, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Days, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panel_typeCourse.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel_typeCourse, java.awt.BorderLayout.CENTER);

        panel_btn.setBackground(new java.awt.Color(255, 255, 255));
        panel_btn.setPreferredSize(new java.awt.Dimension(150, 75));

        jButton1.setBackground(new java.awt.Color(255, 51, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_btnLayout = new javax.swing.GroupLayout(panel_btn);
        panel_btn.setLayout(panel_btnLayout);
        panel_btnLayout.setHorizontalGroup(
            panel_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_btnLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        panel_btnLayout.setVerticalGroup(
            panel_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(panel_btn, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_titleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CourseDTO x;
        OnlineCourseDTO online = null;
        OnsiteCourseDTO onsite =null;
        boolean ck1=false;
        boolean ckonsite=false; 
        boolean ckonline=false;
        if(func.equals("add")){
            x = new CourseDTO();
            x.setCourseID(Integer.parseInt(txt_courseID.getText()));
            x.setCredits(txt_Credit.getText());
            x.setDepartmentID(Integer.parseInt(jcb_deparmentID.getSelectedItem()+""));
            x.setTitle(txt_title.getText());
            if(courseBUS.validateData(x)){
                 ck1=true;
            }else JOptionPane.showMessageDialog(this, "cannot be empty.\nPlease enter valid.", "Notificatioin", 2);
    
            if(jcb_Online.isSelected()&&ck1==true){
                online = new OnlineCourseDTO();
                online.setCourseID(x.getCourseID());
                online.setUrl(txt_url.getText());
                ckonline=true;
                if(onlineCourseBUS.validateData(online)){
                    ck1=true;    
                }else ck1=false;
            }
            if(jcb_onsite.isSelected()&&ck1==true){
                onsite = new OnsiteCourseDTO();
                onsite.setCourseID(x.getCourseID());
                onsite.setLocation(txt_Location.getText());
                onsite.setCourse_time(txt_Time.getText());
                onsite.setDays(txt_Days.getText());
                ckonsite=true;
                try {
                    if(onsiteCourseBUS.validateData(onsite)==true){
                        ck1=true;
                    }else ck1=false;      
                } catch (ParseException ex) {
                    Logger.getLogger(FormCourse.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(ck1==false){
                JOptionPane.showMessageDialog(this, "Add Course Fail - Check Valid", "Notificatioin", 2);
            }
            else{
                courseBUS.AddCourse(x);
                if(ckonline==true) onlineCourseBUS.AddOnlineCourse(online);
                if(ckonsite==true) onsiteCourseBUS.AddOnsiteCourse(onsite);
                JOptionPane.showMessageDialog(this, "Add Course Successful", "Notificatioin", 2);
                MainForm.loadDataCourse2(table);
                dispose();
            }
                    

        }
        else{
            x = new CourseDTO();
            x.setCourseID(Integer.parseInt(txt_courseID.getText()));
            x.setCredits(txt_Credit.getText());
            x.setDepartmentID(Integer.parseInt(jcb_deparmentID.getSelectedItem()+""));
            x.setTitle(txt_title.getText());
            if(courseBUS.validateData(x)){
                 ck1=true;
            }else JOptionPane.showMessageDialog(this, "cannot be empty.\nPlease enter valid.", "Notificatioin", 2);
            if(jcb_Online.isSelected()&&ck1==true){
                online = new OnlineCourseDTO();
                online.setCourseID(x.getCourseID());
                online.setUrl(txt_url.getText());
                ckonline=true;
                if(onlineCourseBUS.validateData(online)){
                    ck1=true;    
                }else ck1=false;
            }
            if(jcb_onsite.isSelected()&&ck1==true){
                onsite = new OnsiteCourseDTO();
                onsite.setCourseID(x.getCourseID());
                onsite.setLocation(txt_Location.getText());
                onsite.setCourse_time(txt_Time.getText());
                onsite.setDays(txt_Days.getText());
                ckonsite=true;
                try {
                    if(onsiteCourseBUS.validateData(onsite)==true){
                        ck1=true;
                    }else ck1=false;      
                } catch (ParseException ex) {
                    Logger.getLogger(FormCourse.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(ck1==false){
                JOptionPane.showMessageDialog(this, "Edit Course Fail - Check Valid", "Notificatioin", 2);
            }
            else{
                courseBUS.UpdateCourse(x);
                if(ckonsite==true){ 
                    if(onsiteCourseBUS.GetOnsiteCourseById(x.getCourseID())!=null)
                        onsiteCourseBUS.UpdateOnsiteCourse(onsite);
                    else 
                        onsiteCourseBUS.AddOnsiteCourse(onsite);
                }
                if(ckonline==true){ 
                    if(onlineCourseBUS.GetOnlineCourseById(x.getCourseID())!=null)
                        onlineCourseBUS.UpdateOnlineCourse(online);
                    else 
                        onlineCourseBUS.AddOnlineCourse(online);
                }
                JOptionPane.showMessageDialog(this, "Edit Course Successful", "Notificatioin", 2);
                    MainForm.loadDataCourse2(table);
                    dispose();
                
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcb_deparmentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_deparmentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_deparmentIDActionPerformed

    private void jcb_OnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_OnlineActionPerformed
        if(jcb_Online.isSelected()){
            txt_url.setEditable(true);
        }
        else txt_url.setEditable(false); 
    }//GEN-LAST:event_jcb_OnlineActionPerformed

    private void jcb_onsiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_onsiteActionPerformed
        if(jcb_onsite.isSelected()){          
            txt_Location.setEditable(true);
            txt_Time.setEditable(true);
            txt_Days.setEditable(true);
        }
        else{    
            txt_Location.setEditable(false);
            txt_Time.setEditable(false);
            txt_Days.setEditable(false);
        }
    }//GEN-LAST:event_jcb_onsiteActionPerformed
    public void renderDataFormShow(String id){
        setTitle("Thông tin khóa học");  
        CourseDTO x = courseBUS.GetCourseById(Integer.parseInt(id));
        txt_courseID.setText(x.getCourseID()+"");
        txt_title.setText(x.getTitle());
        txt_Credit.setText(x.getCredits());
        loadDepartmentid(x.getDepartmentID()+"");  
        if(onlineCourseBUS.GetOnlineCourseById(Integer.parseInt(id))!=null){
            jcb_Online.setSelected(true);
            jcb_Online.setEnabled(false);
            OnlineCourseDTO y = onlineCourseBUS.GetOnlineCourseById(Integer.parseInt(id));
            txt_url.setText(y.getUrl());
        }else{
            txt_url.setEditable(false);
        }  
        if(onsiteCourseBUS.GetOnsiteCourseById(Integer.parseInt(id))!=null){
            jcb_onsite.setSelected(true);
            jcb_onsite.setEnabled(false);
            OnsiteCourseDTO z = onsiteCourseBUS.GetOnsiteCourseById(Integer.parseInt(id));
            txt_Location.setText(z.getLocation());
            txt_Days.setText(z.getDays());
            txt_Time.setText(z.getCourse_time());
        }else{
            
            txt_Location.setEditable(false);
            txt_Time.setEditable(false);
            txt_Days.setEditable(false);
        }
        
        
    }
    public void renderDataFormAdd(){
        setTitle("Thêm khóa học");  
        ArrayList<DepartmentDTO> listDPid= departmentBUS.getList(); 
        for(DepartmentDTO x : listDPid){
            jcb_deparmentID.addItem(x.getDepartmentID()+"");
        }
        txt_courseID.setText(courseBUS.getList().size()+1+"");
        
    }
    public void loadDepartmentid(String key){
        ArrayList<DepartmentDTO> listDPid= departmentBUS.getList(); 
        for(DepartmentDTO x : listDPid){
            jcb_deparmentID.addItem(x.getDepartmentID()+"");
        }
        for(int i=0;i<listDPid.size();i++){
            if(key.equals(jcb_deparmentID.getItemAt(i))) jcb_deparmentID.setSelectedIndex(i);
        }
        
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormDetailCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormDetailCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormDetailCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormDetailCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormDetailCourse().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel information_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox jcb_Online;
    private javax.swing.JComboBox<String> jcb_deparmentID;
    private javax.swing.JCheckBox jcb_onsite;
    private javax.swing.JPanel panel_btn;
    private javax.swing.JPanel panel_typeCourse;
    private javax.swing.JTextField txt_Credit;
    private javax.swing.JTextField txt_Days;
    private javax.swing.JTextField txt_Location;
    private javax.swing.JTextField txt_Time;
    private javax.swing.JLabel txt_courseID;
    private javax.swing.JTextField txt_title;
    private javax.swing.JTextField txt_url;
    // End of variables declaration//GEN-END:variables
}
